[package]
name = "sleitnick/enum-list"
description = "Enum List class"
version = "2.0.2"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
