name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Lint
      run: |
        selene ./modules

  unit-tests:
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download OpenVPN
        run: choco install openvpn

      - name: Run OpenVPN
        run: Start-Process -FilePath "C:\\Program Files\\OpenVPN\\bin\\openvpn.exe" -ArgumentList "--config $(INPUT_OVPN)"
        with:
          ovpn: ${{ secrets.OPENVPN_OVPN }}

      - name: Poll for IP Change
        run: |
          $elapsed = 0
          while ($true) {
            try {
              $response = Invoke-WebRequest -Uri 'https://httpbin.org/ip' -Method GET -UseBasicParsing
              $content = ConvertFrom-Json $response.Content
              if ($content.origin -eq "18.224.110.74") {
                break
              }
            } catch {}
            if ($elapsed -ge 20) {
              Write-Error "Timeout reached!"
              exit 1
            }
            Write-Output "Polling... Elapsed: $elapsed, IP: $($content.origin)"
            Start-Sleep 5
            $elapsed += 5
          }
          Write-Output "Success!"

      - name: Validate Cookie
        run: |
          $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
          $cookie = New-Object System.Net.Cookie
          $cookie.Name = ".ROBLOSECURITY"
          $cookie.Value = "${{ secrets.ROBLOSECURITY }}"
          $cookie.Domain = ".roblox.com"
          $session.Cookies.Add($cookie);
          Invoke-WebRequest "https://avatar.roblox.com/v1/avatar" -WebSession $session -UseBasicParsing

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tests
        run: python build_tests.py

      - name: Build test place
        run: rojo build default.project.json -o test.rbxl

      - name: Run tests
        run: run-in-roblox --place test.rbxl --script ci\\unit.server.lua > test-out.txt
        continue-on-error: true
        timeout-minutes: 3
        
      - name: Check test status
        shell: bash
        run: cat test-out.txt | grep "0 failed, 0 skipped" || (cat test-out.txt && exit 1)
